codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project: true
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "sunburst"
  behavior: default
  require_changes: false
